<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Videotoy.Media</RootNamespace>
    <AssemblyName>Videotoy.Media</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Videotoy.Core\Videotoy.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
  </ItemGroup>

</Project>
