<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Videotoy.Rendering</RootNamespace>
    <AssemblyName>Videotoy.Rendering</AssemblyName>
    <UseWindowsForms>false</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Videotoy.Core\Videotoy.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.6.2" />
    <PackageReference Include="Vortice.DXGI" Version="3.6.2" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.6.2" />
  </ItemGroup>

</Project>
