using System.Collections.ObjectModel;
using System.IO;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Win32;
using Videotoy.Core.Domain;
using Videotoy.Ffmpeg;
using Videotoy.Media;
using Videotoy.Rendering;
using CoreFileSizeEstimator = Videotoy.Core.ExportFileSizeEstimator;
using CoreLoopCalculator = Videotoy.Core.LoopCalculator;

namespace Videotoy.App.ViewModels;

public sealed partial class MainWindowViewModel : ObservableObject
{
    private static readonly string[] OpenFileDialogExtensions =
        { "*.glsl", "*.frag", "*.json", "*.shadertoy" };

    private readonly ShaderFileService _shaderFileService;
    private readonly RecentFilesService _recentFilesService;
    private readonly ExportPresetService _exportPresetService;
    private readonly LoopSettingsService _loopSettingsService;
    private readonly LocalizationService _localizationService;
    private readonly MultiPassRenderer _previewRenderer;
    private readonly PreviewClock _previewClock = new();
    private readonly IShaderRenderer _exportRenderer;
    private readonly VideoExportPipeline _exportPipeline;

    private WriteableBitmap? _previewBitmap;
    private LoadedShader? _loadedShader;
    private bool _isScrubbing;
    private CancellationTokenSource? _exportCancellationTokenSource;

    [ObservableProperty]
    private string _statusMessage = "Idle";

    [ObservableProperty]
    private int _currentFrame;

    [ObservableProperty]
    private int _totalFrames;

    [ObservableProperty]
    private double _currentFps;

    [ObservableProperty]
    private bool _isSettingsPanelOpen = true;

    [ObservableProperty]
    private string _loadedShaderName = string.Empty;

    [ObservableProperty]
    private bool _isShaderLoaded;

    [ObservableProperty]
    private bool _isIssuesPanelOpen;

    [ObservableProperty]
    private bool _isPlaying;

    [ObservableProperty]
    private double _playbackTimeSeconds;

    [ObservableProperty]
    private double _loopDurationSeconds = 10.0;

    [ObservableProperty]
    private ImageSource? _previewImageSource;

    /// <summary>
    /// First frame (t = 0) of the current "Seamless loop" configuration, as
    /// last generated by <see cref="GenerateLoopSeamPreviewCommand"/>. Null
    /// until the command has run at least once for the currently loaded
    /// shader/settings combination.
    /// </summary>
    [ObservableProperty]
    private ImageSource? _loopSeamStartFrameImageSource;

    /// <summary>
    /// Last frame actually rendered for export under the current "Seamless
    /// loop" configuration (index <c>EstimatedTotalFrames - 1</c>), as last
    /// generated by <see cref="GenerateLoopSeamPreviewCommand"/> — i.e. the
    /// frame immediately preceding the loop restart, which should look like
    /// a natural predecessor of <see cref="LoopSeamStartFrameImageSource"/>
    /// for the loop to read as seamless.
    /// </summary>
    [ObservableProperty]
    private ImageSource? _loopSeamEndFrameImageSource;

    /// <summary>
    /// True while <see cref="GenerateLoopSeamPreviewCommand"/> is rendering
    /// the loop sequence; disables the button and shows a busy indicator
    /// rather than freezing the panel silently, since a long loop at a high
    /// frame rate can take a noticeable moment to walk through.
    /// </summary>
    [ObservableProperty]
    private bool _isGeneratingLoopSeamPreview;

    /// <summary>
    /// True once <see cref="LoopSeamStartFrameImageSource"/> and
    /// <see cref="LoopSeamEndFrameImageSource"/> hold a result, so the panel
    /// can show the side-by-side comparison. Reset to false whenever a
    /// setting that would invalidate the preview changes (shader reload,
    /// resolution/frame-rate/loop-duration/exclusive-end-frame change) so a
    /// stale comparison is never shown as if it were current.
    /// </summary>
    [ObservableProperty]
    private bool _hasLoopSeamPreview;

    /// <summary>
    /// Currently selected export resolution preset. Switching to
    /// <see cref="ResolutionPresetOption.Custom"/> reveals the custom
    /// width/height inputs; any other preset directly supplies the export
    /// resolution and disables those inputs.
    /// </summary>
    [ObservableProperty]
    private ResolutionPresetOption _selectedResolutionPreset = ResolutionPresetOption.FullHd1080;

    [ObservableProperty]
    private int _customResolutionWidth = 1920;

    [ObservableProperty]
    private int _customResolutionHeight = 1080;

    /// <summary>
    /// Currently selected export frame rate preset. Switching to
    /// <see cref="FrameRatePresetOption.Custom"/> reveals the custom frame
    /// rate input; any other preset directly supplies the export frame rate
    /// and disables that input.
    /// </summary>
    [ObservableProperty]
    private FrameRatePresetOption _selectedFrameRatePreset = FrameRatePresetOption.Fps30;

    [ObservableProperty]
    private double _customFrameRateValue = 30.0;

    /// <summary>
    /// Unit in which <see cref="ManualDurationValue"/> is expressed when the
    /// export duration mode is "Manual duration". Ignored in "Seamless loop"
    /// mode, which always uses <see cref="LoopDurationSeconds"/> directly.
    /// </summary>
    [ObservableProperty]
    private DurationUnit _manualDurationUnit = DurationUnit.Seconds;

    /// <summary>
    /// Zero-based index proxy for <see cref="ManualDurationUnit"/>
    /// (0 = Seconds, 1 = Frames), so the "Seconds/Frames" combo box in the
    /// panel can bind <c>SelectedIndex</c> directly without a value
    /// converter.
    /// </summary>
    public int ManualDurationUnitIndex
    {
        get => (int)ManualDurationUnit;
        set => ManualDurationUnit = (DurationUnit)value;
    }

    /// <summary>
    /// Manual export duration, expressed in <see cref="ManualDurationUnit"/>
    /// (seconds or frames). Converted to seconds against the effective export
    /// frame rate before being handed to <see cref="DurationMode.NewManual"/>.
    /// </summary>
    [ObservableProperty]
    private double _manualDurationValue = 10.0;

    /// <summary>
    /// Absolute path of the folder the exported video will be written to.
    /// Defaults to the user's Videos folder and is editable directly or via
    /// <see cref="BrowseOutputDirectoryCommand"/>.
    /// </summary>
    [ObservableProperty]
    private string _outputDirectory =
        Environment.GetFolderPath(Environment.SpecialFolder.MyVideos);

    /// <summary>
    /// Output file name (without the container extension, which is appended
    /// automatically from <see cref="Videotoy.Core.Domain.ContainerFormat"/>
    /// at export time). Defaults to the loaded shader's title once a shader
    /// is loaded.
    /// </summary>
    [ObservableProperty]
    private string _outputFileName = "export";

    /// <summary>
    /// Total number of frames the current export configuration will produce,
    /// recomputed from <see cref="LoopCalculator.computeFrameCount"/> every
    /// time a setting that affects it changes. Drives the frame-count and
    /// estimated file-size preview in the render settings panel.
    /// </summary>
    [ObservableProperty]
    private int _estimatedTotalFrames;

    /// <summary>
    /// Human-readable estimated output file size ("~12.4 MB"), recomputed
    /// alongside <see cref="EstimatedTotalFrames"/>. Purely informational —
    /// see <see cref="Videotoy.Core.ExportFileSizeEstimator"/>.
    /// </summary>
    [ObservableProperty]
    private string _estimatedFileSizeText = "-";

    /// <summary>
    /// True when <see cref="LoopCalculator.computeFrameCount"/> reports that
    /// the requested duration doesn't divide evenly into whole frames at the
    /// selected frame rate ("Seamless loop" mode only) — surfaced in the
    /// panel as a rounding-mismatch warning.
    /// </summary>
    [ObservableProperty]
    private bool _hasLoopRoundingMismatch;

    /// <summary>
    /// Nearest loop duration (in seconds) that divides evenly into whole
    /// frames at the currently selected export frame rate, as computed by
    /// <see cref="LoopCalculator.suggestAssistedLoopSeconds"/>. Only
    /// meaningful — and only surfaced in the panel — while
    /// <see cref="HasLoopRoundingMismatch"/> is true; applying it via
    /// <see cref="ApplyAssistedLoopRoundingCommand"/> removes the mismatch
    /// entirely rather than merely reducing it.
    /// </summary>
    [ObservableProperty]
    private double _suggestedLoopDurationSeconds;

    /// <summary>
    /// True once <see cref="Videotoy.Core.LoopPeriodDetector.detectLoopPeriod"/>
    /// has found at least one candidate native loop period in the currently
    /// loaded shader's source (simple periodic patterns on <c>iTime</c>,
    /// e.g. <c>sin(iTime * K)</c> or <c>mod(iTime, K)</c>) — purely a
    /// heuristic, never guaranteed for complex shaders. Drives the
    /// visibility of the "Detected loop period" hint in the panel; recomputed
    /// once per shader load, never re-run automatically afterwards.
    /// </summary>
    [ObservableProperty]
    private bool _hasDetectedLoopPeriod;

    /// <summary>
    /// The suggested native loop period (in seconds), as returned by
    /// <see cref="Videotoy.Core.LoopPeriodDetector.detectLoopPeriod"/>'s
    /// <c>SuggestedCandidate</c> — the longest period among every simple
    /// periodic pattern detected in the shader's source. Only meaningful
    /// while <see cref="HasDetectedLoopPeriod"/> is true. Never applied
    /// automatically: <see cref="ApplyDetectedLoopPeriodCommand"/> is the
    /// only way it reaches <see cref="LoopDurationSeconds"/>, and only when
    /// the user explicitly triggers it.
    /// </summary>
    [ObservableProperty]
    private double _detectedLoopPeriodSeconds;

    /// <summary>
    /// True when more than one independent periodic pattern was found in
    /// the shader's source (e.g. a slow rotation and a fast flicker), so the
    /// panel can note that the suggested period is the longest detected one
    /// among several, not the only candidate found.
    /// </summary>
    [ObservableProperty]
    private bool _hasMultipleDetectedLoopPeriods;

    /// <summary>
    /// Short human-readable description of where
    /// <see cref="DetectedLoopPeriodSeconds"/> came from (source expression
    /// and pass name), shown alongside the suggestion so the user can judge
    /// for themselves whether it's trustworthy before applying it.
    /// </summary>
    [ObservableProperty]
    private string _detectedLoopPeriodSourceText = string.Empty;

    /// <summary>
    /// True when the export duration mode is "Seamless loop"
    /// (<see cref="LoopDurationSeconds"/>), false for "Manual duration"
    /// (<see cref="ManualDurationValue"/> / <see cref="ManualDurationUnit"/>).
    /// Bound to the two radio buttons in the "Duration Mode" card.
    /// </summary>
    [ObservableProperty]
    private bool _isSeamlessLoopModeEnabled;

    /// <summary>
    /// "Frame de fin exclusive" toggle, "Seamless loop" mode only. When true
    /// (default), the frame at <c>t = LoopDurationSeconds</c> — identical to
    /// the frame at <c>t = 0</c> of the next cycle — is never rendered, so
    /// looped playback never shows a duplicated frame at the seam. When
    /// false, that end frame is rendered and included in the export, one
    /// frame longer than the exclusive case. Fed into
    /// <see cref="DurationMode.NewSeamlessLoop"/>'s <c>excludeEndFrame</c>
    /// argument via <see cref="ResolveDurationMode"/>.
    /// </summary>
    [ObservableProperty]
    private bool _isLoopEndFrameExclusive = true;

    public IReadOnlyList<ResolutionPresetOption> ResolutionPresets => ResolutionPresetOption.All;

    public IReadOnlyList<FrameRatePresetOption> FrameRatePresets => FrameRatePresetOption.All;

    [ObservableProperty]
    private bool _isExporting;

    [ObservableProperty]
    private int _exportCurrentFrame;

    [ObservableProperty]
    private int _exportTotalFrames;

    [ObservableProperty]
    private double _exportProgressPercent;

    [ObservableProperty]
    private string _exportRemainingTimeText = string.Empty;

    [ObservableProperty]
    private bool _hasExportError;

    [ObservableProperty]
    private string _exportErrorSummary = string.Empty;

    /// <summary>
    /// Mode "petite config" : introduit un throttling volontaire entre chaque
    /// frame rendue pendant l'export, pour ne pas saturer le CPU/GPU sur une
    /// machine modeste. L'export reste séquentiel et sans perte de frame dans
    /// les deux cas ; seul le rythme change.
    /// </summary>
    [ObservableProperty]
    private bool _isLowSpecModeEnabled;

    /// <summary>
    /// Vrai lorsque le shader actuellement chargé déclare au moins un
    /// <c>iChannel</c> audio (<c>Music</c>/<c>MusicStream</c>) dont le
    /// fichier source résolu existe sur disque — c'est-à-dire lorsqu'une
    /// piste audio peut effectivement être muxée à l'export. Piloté par
    /// <see cref="ResolveExportAudioSourceFilePath"/>, recalculé à chaque
    /// chargement de shader. Contrôle l'affichage de l'option « Vidéo sans
    /// son » / « Vidéo avec son » dans le panneau de paramètres de rendu.
    /// </summary>
    [ObservableProperty]
    private bool _hasAudioChannel;

    /// <summary>
    /// Choix de l'utilisateur d'inclure ou non la piste audio détectée dans
    /// la vidéo exportée, lorsque <see cref="HasAudioChannel"/> est vrai.
    /// Actif par défaut : quand un shader avec `iChannel` audio est chargé,
    /// l'export inclut le son sauf décision explicite contraire. Sans effet
    /// tant qu'aucune piste audio n'est détectée.
    /// </summary>
    [ObservableProperty]
    private bool _includeAudioInExport = true;

    private const int LowSpecThrottleMillisecondsPerFrame = 50;

    public ObservableCollection<RecentShaderFile> RecentShaders { get; } = new();

    public ObservableCollection<ShaderIssueViewModel> ShaderIssues { get; } = new();

    public ObservableCollection<ExportPreset> ExportPresets { get; } = new();

    /// <summary>
    /// Currently visible toast notifications (export success/failure, etc.),
    /// newest last. Each entry is removed automatically after
    /// <see cref="ToastDisplayDuration"/> via <see cref="ShowToast"/>'s
    /// dispatcher timer, or immediately via <see cref="DismissToastCommand"/>
    /// if the user closes it early.
    /// </summary>
    public ObservableCollection<ToastNotificationViewModel> Toasts { get; } = new();

    /// <summary>
    /// Groupes de sliders (un groupe par uniform custom, un slider par
    /// composant) reflétant les uniforms custom exposés par le shader
    /// actuellement chargé — voir <see cref="Videotoy.Core.CustomUniformParser"/>
    /// et <see cref="MultiPassRenderer.CustomUniformDeclarations"/>.
    /// Reconstruite entièrement à chaque chargement de shader ; vide tant
    /// qu'aucun shader n'expose d'uniform custom.
    /// </summary>
    public ObservableCollection<CustomUniformGroupViewModel> CustomUniformGroups { get; } = new();

    /// <summary>
    /// Vrai lorsque le shader chargé expose au moins un uniform custom,
    /// pilote l'affichage de la card "Custom Uniforms" du panneau de
    /// paramètres de rendu.
    /// </summary>
    [ObservableProperty]
    private bool _hasCustomUniforms;

    /// <summary>
    /// Preset currently selected in the "Load preset" combo box. Loading
    /// (<see cref="LoadExportPresetCommand"/>) applies it to every panel
    /// input it covers; it does not itself change any setting until the
    /// command runs.
    /// </summary>
    [ObservableProperty]
    private ExportPreset? _selectedExportPreset;

    /// <summary>
    /// Name typed into the "Save preset" field. Saving
    /// (<see cref="SaveExportPresetCommand"/>) replaces any existing preset
    /// with the same name (case-insensitive) rather than accumulating
    /// duplicates — see <see cref="ExportPresetService.SaveOrReplace"/>.
    /// </summary>
    [ObservableProperty]
    private string _newExportPresetName = string.Empty;

    public MainWindowViewModel(
        ShaderFileService shaderFileService,
        RecentFilesService recentFilesService,
        ExportPresetService exportPresetService,
        LoopSettingsService loopSettingsService,
        LocalizationService localizationService,
        MultiPassRenderer previewRenderer,
        IShaderRenderer exportRenderer,
        VideoExportPipeline exportPipeline)
    {
        _shaderFileService = shaderFileService;
        _recentFilesService = recentFilesService;
        _exportPresetService = exportPresetService;
        _loopSettingsService = loopSettingsService;
        _localizationService = localizationService;
        _previewRenderer = previewRenderer;
        _exportRenderer = exportRenderer;
        _exportPipeline = exportPipeline;
        _previewClock.LoopDurationSeconds = _loopDurationSeconds;
        _previewClock.TimeChanged += OnPreviewClockTimeChanged;

        ReloadRecentShaders();
        ReloadExportPresets();
        RecalculateExportPreview();
    }

    /// <summary>
    /// Effective export resolution: the selected preset's fixed dimensions,
    /// or <see cref="CustomResolutionWidth"/>/<see cref="CustomResolutionHeight"/>
    /// when <see cref="SelectedResolutionPreset"/> is
    /// <see cref="ResolutionPresetOption.Custom"/>.
    /// </summary>
    private Resolution ResolveExportResolution() =>
        SelectedResolutionPreset.IsCustom
            ? new Resolution(Math.Max(0, CustomResolutionWidth), Math.Max(0, CustomResolutionHeight))
            : new Resolution(SelectedResolutionPreset.Width, SelectedResolutionPreset.Height);

    /// <summary>
    /// Effective export frame rate: the selected preset's fixed value, or
    /// <see cref="CustomFrameRateValue"/> when <see cref="SelectedFrameRatePreset"/>
    /// is <see cref="FrameRatePresetOption.Custom"/>.
    /// </summary>
    private FrameRate ResolveExportFrameRate() =>
        new(SelectedFrameRatePreset.IsCustom ? CustomFrameRateValue : SelectedFrameRatePreset.Value);

    /// <summary>
    /// Builds the effective <see cref="DurationMode"/> for the current panel
    /// state: "Seamless loop" always uses <see cref="LoopDurationSeconds"/>
    /// directly, while "Manual duration" converts <see cref="ManualDurationValue"/>
    /// from <see cref="ManualDurationUnit"/> (seconds or frames) into seconds
    /// against <paramref name="frameRate"/>.
    /// </summary>
    private DurationMode ResolveDurationMode(FrameRate frameRate)
    {
        if (IsSeamlessLoopModeEnabled)
        {
            return DurationMode.NewSeamlessLoop(LoopDurationSeconds, IsLoopEndFrameExclusive);
        }

        var seconds = ManualDurationUnit == DurationUnit.Frames && frameRate.Value > 0.0
            ? ManualDurationValue / frameRate.Value
            : ManualDurationValue;

        return DurationMode.NewManual(seconds);
    }

    /// <summary>
    /// Applies <see cref="SuggestedLoopDurationSeconds"/> to
    /// <see cref="LoopDurationSeconds"/>, replacing the current loop duration
    /// with the nearest one that divides evenly into whole frames at the
    /// selected export frame rate — eliminating
    /// <see cref="HasLoopRoundingMismatch"/> entirely. Never invoked
    /// automatically: the mismatch warning offers this as an explicit,
    /// user-triggered action rather than a silent adjustment.
    /// </summary>
    [RelayCommand(CanExecute = nameof(HasLoopRoundingMismatch))]
    private void ApplyAssistedLoopRounding()
    {
        LoopDurationSeconds = SuggestedLoopDurationSeconds;
    }

    /// <summary>
    /// Applies <see cref="DetectedLoopPeriodSeconds"/> to
    /// <see cref="LoopDurationSeconds"/> — the only way the heuristically
    /// detected native loop period ever reaches an actual export setting.
    /// Purely a proposed, editable default: never applied automatically on
    /// shader load, and the user remains free to type any other value
    /// afterwards regardless of what was detected.
    /// </summary>
    [RelayCommand(CanExecute = nameof(HasDetectedLoopPeriod))]
    private void ApplyDetectedLoopPeriod()
    {
        LoopDurationSeconds = DetectedLoopPeriodSeconds;
    }

    [RelayCommand]
    private void BrowseOutputDirectory()
    {
        var dialog = new OpenFolderDialog
        {
            Multiselect = false,
            InitialDirectory = Directory.Exists(OutputDirectory)
                ? OutputDirectory
                : Environment.GetFolderPath(Environment.SpecialFolder.MyVideos)
        };

        if (dialog.ShowDialog() == true && !string.IsNullOrWhiteSpace(dialog.FolderName))
        {
            OutputDirectory = dialog.FolderName;
        }
    }

    /// <summary>
    /// Saves the current render settings panel state (resolution, frame
    /// rate, duration mode, low-spec mode — deliberately not the output
    /// folder/file name, which are per-export rather than part of a reusable
    /// preset) as an <see cref="ExportPreset"/> named
    /// <see cref="NewExportPresetName"/>. Replaces any existing preset with
    /// the same name. No-op if the name is blank.
    /// </summary>
    [RelayCommand(CanExecute = nameof(CanSaveExportPreset))]
    private void SaveExportPreset()
    {
        var preset = new ExportPreset
        {
            Name = NewExportPresetName.Trim(),
            ResolutionPresetName = SelectedResolutionPreset.Key,
            CustomResolutionWidth = CustomResolutionWidth,
            CustomResolutionHeight = CustomResolutionHeight,
            FrameRatePresetName = SelectedFrameRatePreset.Key,
            CustomFrameRateValue = CustomFrameRateValue,
            IsSeamlessLoopModeEnabled = IsSeamlessLoopModeEnabled,
            ManualDurationUnit = ManualDurationUnit.ToString(),
            ManualDurationValue = ManualDurationValue,
            LoopDurationSeconds = LoopDurationSeconds,
            IsLoopEndFrameExclusive = IsLoopEndFrameExclusive,
            IsLowSpecModeEnabled = IsLowSpecModeEnabled
        };

        _exportPresetService.SaveOrReplace(preset);
        ReloadExportPresets();
        SelectedExportPreset = ExportPresets.FirstOrDefault(
            entry => string.Equals(entry.Name, preset.Name, StringComparison.OrdinalIgnoreCase));
        NewExportPresetName = string.Empty;
        StatusMessage = $"Saved export preset '{preset.Name}'.";
    }

    private bool CanSaveExportPreset() => !string.IsNullOrWhiteSpace(NewExportPresetName);

    /// <summary>
    /// Applies <see cref="SelectedExportPreset"/> to every panel input it
    /// covers. Each setter goes through the normal property (rather than the
    /// backing field) so the usual <c>partial void On...Changed</c> hooks
    /// still fire and <see cref="RecalculateExportPreview"/> stays in sync.
    /// No-op if nothing is selected.
    /// </summary>
    [RelayCommand(CanExecute = nameof(CanLoadExportPreset))]
    private void LoadExportPreset()
    {
        if (SelectedExportPreset is not { } preset)
        {
            return;
        }

        SelectedResolutionPreset = ResolutionPresetOption.FromKey(preset.ResolutionPresetName);
        CustomResolutionWidth = preset.CustomResolutionWidth;
        CustomResolutionHeight = preset.CustomResolutionHeight;
        SelectedFrameRatePreset = FrameRatePresetOption.FromKey(preset.FrameRatePresetName);
        CustomFrameRateValue = preset.CustomFrameRateValue;
        IsSeamlessLoopModeEnabled = preset.IsSeamlessLoopModeEnabled;
        ManualDurationUnit = Enum.TryParse<DurationUnit>(preset.ManualDurationUnit, out var unit)
            ? unit
            : DurationUnit.Seconds;
        ManualDurationValue = preset.ManualDurationValue;
        LoopDurationSeconds = preset.LoopDurationSeconds;
        IsLoopEndFrameExclusive = preset.IsLoopEndFrameExclusive;
        IsLowSpecModeEnabled = preset.IsLowSpecModeEnabled;

        StatusMessage = $"Loaded export preset '{preset.Name}'.";
    }

    private bool CanLoadExportPreset() => SelectedExportPreset is not null;

    [RelayCommand(CanExecute = nameof(CanLoadExportPreset))]
    private void DeleteExportPreset()
    {
        if (SelectedExportPreset is not { } preset)
        {
            return;
        }

        _exportPresetService.Delete(preset.Name);
        ReloadExportPresets();
        SelectedExportPreset = null;
        StatusMessage = $"Deleted export preset '{preset.Name}'.";
    }

    private void ReloadExportPresets()
    {
        ExportPresets.Clear();
        foreach (var preset in _exportPresetService.Load())
        {
            ExportPresets.Add(preset);
        }
    }

    /// <summary>
    /// Recomputes <see cref="EstimatedTotalFrames"/>,
    /// <see cref="EstimatedFileSizeText"/> and <see cref="HasLoopRoundingMismatch"/>
    /// from the current resolution/frame-rate/duration panel state. Called
    /// whenever any input feeding <see cref="LoopCalculator.computeFrameCount"/>
    /// or <see cref="ExportFileSizeEstimator.estimateFileSizeBytes"/> changes.
    /// </summary>
    private void RecalculateExportPreview()
    {
        var resolution = ResolveExportResolution();
        var frameRate = ResolveExportFrameRate();
        var durationMode = ResolveDurationMode(frameRate);

        var frameCountResult = CoreLoopCalculator.computeFrameCount(durationMode, frameRate);
        EstimatedTotalFrames = Math.Max(0, frameCountResult.FrameCount);
        HasLoopRoundingMismatch = IsSeamlessLoopModeEnabled && frameCountResult.HasRoundingMismatch;
        SuggestedLoopDurationSeconds = HasLoopRoundingMismatch
            ? CoreLoopCalculator.suggestAssistedLoopSeconds(LoopDurationSeconds, frameRate)
            : LoopDurationSeconds;

        var estimatedBytes = CoreFileSizeEstimator.estimateFileSizeBytes(
            resolution,
            frameRate,
            RateControlMode.NewConstantRateFactor(18),
            EstimatedTotalFrames,
            HasAudioChannel && IncludeAudioInExport);

        EstimatedFileSizeText = CoreFileSizeEstimator.formatEstimatedFileSize(estimatedBytes);

        // Toute entrée qui affecte le nombre/le contenu des frames rendues
        // (résolution, fps, mode de durée, valeur/unité, frame de fin
        // exclusive) invalide une comparaison de raccord déjà affichée :
        // elle ne refléterait plus la configuration actuelle.
        HasLoopSeamPreview = false;
        GenerateLoopSeamPreviewCommand.NotifyCanExecuteChanged();
    }

    [RelayCommand]
    private void ToggleSettingsPanel()
    {
        IsSettingsPanelOpen = !IsSettingsPanelOpen;
    }

    [RelayCommand]
    private void OpenShader()
    {
        var dialog = new OpenFileDialog
        {
            Filter = "Shader files|" + string.Join(";", OpenFileDialogExtensions) + "|All files|*.*"
        };

        if (dialog.ShowDialog() == true)
        {
            LoadShaderFile(dialog.FileName);
        }
    }

    [RelayCommand]
    private void OpenRecentShader(string filePath)
    {
        LoadShaderFile(filePath);
    }

    [RelayCommand]
    private void CloseIssuesPanel()
    {
        IsIssuesPanelOpen = false;
    }

    [RelayCommand(CanExecute = nameof(IsShaderLoaded))]
    private void TogglePlayback()
    {
        _previewClock.TogglePlayback();
        IsPlaying = _previewClock.IsPlaying;
    }

    [RelayCommand(CanExecute = nameof(IsShaderLoaded))]
    private void StopPlayback()
    {
        _previewClock.Stop();
        IsPlaying = false;
        RenderCurrentFrame();
    }

    /// <summary>
    /// Débute un scrub manuel de la timeline : met la lecture en pause pendant
    /// que l'utilisateur fait glisser le curseur, sans perdre l'état "lecture en
    /// cours" une fois le scrub terminé.
    /// </summary>
    [RelayCommand]
    private void BeginScrub()
    {
        _isScrubbing = true;
        _previewClock.Pause();
    }

    [RelayCommand]
    private void EndScrub()
    {
        _isScrubbing = false;
        if (IsPlaying)
        {
            _previewClock.Play();
        }
    }

    /// <summary>
    /// Positionne la lecture sur une valeur de timeline arbitraire (drag du curseur
    /// de progression), en secondes.
    /// </summary>
    public void Seek(double timeSeconds)
    {
        _previewClock.Seek(timeSeconds);
    }

    /// <summary>
    /// Renders the first (t = 0) and last (index EstimatedTotalFrames - 1)
    /// frames of the current "Seamless loop" configuration side by side,
    /// letting the user visually validate the loop seam before committing to
    /// a full export. Only enabled while a shader is loaded and "Seamless
    /// loop" duration mode is selected.
    /// </summary>
    /// <remarks>
    /// Walks <see cref="_previewRenderer"/> through the entire loop timeline
    /// (frame 0 through the last exported frame) — not just those two frames
    /// in isolation — because a shader with a self-referencing buffer (Buffer
    /// A/B/C/D ping-pong feedback) accumulates state frame by frame; jumping
    /// straight to the last frame's timestamp without having rendered every
    /// frame before it would show a buffer state the real export never
    /// produces. This uses the same deterministic timeline construction as
    /// the actual export (<see cref="CoreLoopCalculator.computeFrameCount"/> /
    /// <see cref="CoreLoopCalculator.buildFrameTimeline"/>), at the fixed
    /// preview resolution/renderer rather than the export resolution/renderer,
    /// so the comparison is representative of the loop's motion without
    /// paying the cost of a full-resolution render.
    ///
    /// Runs synchronously on the UI thread rather than on a background task:
    /// <see cref="_previewRenderer"/> owns a single, non-thread-safe D3D11
    /// device shared with the live viewport, so off-thread rendering would
    /// risk a device-context race with the live playback loop
    /// (<see cref="AdvancePreview"/>) rather than actually speeding anything
    /// up. For a long loop at a high frame rate this can briefly freeze the
    /// panel; <see cref="IsGeneratingLoopSeamPreview"/> at least disables the
    /// button and swaps its label to "Generating..." so the freeze reads as
    /// expected rather than as a hang.
    ///
    /// Advancing the shared <see cref="_previewRenderer"/> through this
    /// sequence leaves its internal ping-pong buffer state at the loop's end
    /// rather than at the live playback position; once done, the current
    /// live-playback frame is re-rendered immediately afterward so the
    /// viewport's next displayed frame is visually correct again (the ping-
    /// pong buffers briefly reflect a different frame index than
    /// <see cref="CurrentFrame"/>, which only affects self-referencing
    /// buffers' feedback for one further live frame and self-corrects
    /// immediately, since every subsequent live frame re-renders from the
    /// buffers' actual current contents).
    /// </remarks>
    [RelayCommand(CanExecute = nameof(CanGenerateLoopSeamPreview))]
    private void GenerateLoopSeamPreview()
    {
        if (_loadedShader is null)
        {
            return;
        }

        IsGeneratingLoopSeamPreview = true;
        HasLoopSeamPreview = false;

        try
        {
            var frameRate = ResolveExportFrameRate();
            var durationMode = ResolveDurationMode(frameRate);
            var frameCountResult = CoreLoopCalculator.computeFrameCount(durationMode, frameRate);

            if (frameCountResult.FrameCount <= 0)
            {
                return;
            }

            var timeline = CoreLoopCalculator.buildFrameTimeline(frameCountResult.FrameCount, frameRate);

            byte[]? startPixels = null;
            byte[]? endPixels = null;

            foreach (var frame in timeline)
            {
                var pixels = _previewRenderer.RenderFrame(frame.TimeSeconds, frame.DeltaSeconds, frame.Index);

                if (frame.Index == 0)
                {
                    startPixels = pixels;
                }

                if (frame.Index == frameCountResult.FrameCount - 1)
                {
                    endPixels = pixels;
                }
            }

            if (startPixels is { Length: > 0 } && endPixels is { Length: > 0 })
            {
                LoopSeamStartFrameImageSource = CreatePreviewBitmap(startPixels);
                LoopSeamEndFrameImageSource = CreatePreviewBitmap(endPixels);
                HasLoopSeamPreview = true;
            }
        }
        finally
        {
            // Resynchronise le viewport live sur sa position de lecture réelle
            // avant de rendre la main : le renderer partagé vient d'avancer à
            // travers toute la timeline de boucle pour générer la comparaison.
            RenderCurrentFrame();
            IsGeneratingLoopSeamPreview = false;
        }
    }

    private bool CanGenerateLoopSeamPreview() =>
        IsShaderLoaded && IsSeamlessLoopModeEnabled && !IsExporting && !IsGeneratingLoopSeamPreview;

    private static WriteableBitmap CreatePreviewBitmap(byte[] pixelsRgba)
    {
        var bitmap = new WriteableBitmap(
            RenderTargetSize.PreviewDefault.Width,
            RenderTargetSize.PreviewDefault.Height,
            96,
            96,
            PixelFormats.Bgra32,
            null);

        bitmap.WritePixels(
            new System.Windows.Int32Rect(0, 0, bitmap.PixelWidth, bitmap.PixelHeight),
            pixelsRgba,
            bitmap.PixelWidth * 4,
            0);

        return bitmap;
    }

    [RelayCommand(CanExecute = nameof(CanExportVideo))]
    private async Task ExportVideoAsync()
    {
        if (_loadedShader is null)
        {
            return;
        }

        var frameRate = ResolveExportFrameRate();
        var exportSettings = new ExportSettings(
            ResolveExportResolution(),
            frameRate,
            ResolveDurationMode(frameRate),
            OutputDirectory,
            OutputFileName,
            VideoCodec.H264,
            RateControlMode.NewConstantRateFactor(18),
            ContainerFormat.Mp4,
            IsLowSpecModeEnabled
                ? PerformanceMode.NewLowSpec(LowSpecThrottleMillisecondsPerFrame)
                : PerformanceMode.Normal);

        var validationIssues = Videotoy.Core.ExportSettingsValidator.validate(exportSettings);
        if (!validationIssues.IsEmpty)
        {
            HasExportError = true;
            ExportErrorSummary = DescribeFirstValidationIssue(validationIssues);
            StatusMessage = $"Export failed: {ExportErrorSummary}";
            ShowToast(
                ToastSeverity.Error,
                _localizationService.GetString("toast.export.error.title"),
                ExportErrorSummary);
            return;
        }

        var outputFilePath = Videotoy.Core.ExportSettingsValidator.resolveOutputFilePath(exportSettings);

        IsExporting = true;
        ExportCurrentFrame = 0;
        ExportTotalFrames = 0;
        ExportProgressPercent = 0.0;
        ExportRemainingTimeText = string.Empty;
        HasExportError = false;
        ExportErrorSummary = string.Empty;
        StatusMessage = "Exporting...";

        _exportCancellationTokenSource = new CancellationTokenSource();
        var progress = new Progress<VideoExportProgress>(OnExportProgress);
        var audioSourceFilePath = HasAudioChannel && IncludeAudioInExport
            ? ResolveExportAudioSourceFilePath(_loadedShader)
            : null;

        try
        {
            _exportRenderer.Initialize(new RenderTargetSize(exportSettings.Resolution.Width, exportSettings.Resolution.Height));
            _exportRenderer.LoadShader(_loadedShader.HlslPasses["Image"].HlslSource);

            await _exportPipeline.RunAsync(exportSettings, progress, _exportCancellationTokenSource.Token, audioSourceFilePath);

            StatusMessage = $"Export complete: {outputFilePath}";
            ShowToast(
                ToastSeverity.Success,
                _localizationService.GetString("toast.export.success.title"),
                outputFilePath);
        }
        catch (OperationCanceledException)
        {
            StatusMessage = "Export cancelled.";
        }
        catch (FfmpegEncodingException ex)
        {
            HasExportError = true;
            ExportErrorSummary = ex.Diagnosis.Summary;
            StatusMessage = $"Export failed: {ex.Diagnosis.Summary}";
            ShowToast(
                ToastSeverity.Error,
                _localizationService.GetString("toast.export.error.title"),
                ex.Diagnosis.Summary);
        }
        catch (Exception ex)
        {
            HasExportError = true;
            ExportErrorSummary = ex.Message;
            StatusMessage = $"Export failed: {ex.Message}";
            ShowToast(
                ToastSeverity.Error,
                _localizationService.GetString("toast.export.error.title"),
                ex.Message);
        }
        finally
        {
            IsExporting = false;
            _exportCancellationTokenSource?.Dispose();
            _exportCancellationTokenSource = null;
        }
    }

    /// <summary>
    /// Strips characters invalid in a Windows file name from the loaded
    /// shader's title, so it can be used as the default
    /// <see cref="OutputFileName"/> without the user having to edit it first.
    /// Falls back to <c>"export"</c> if nothing usable remains.
    /// </summary>
    private static string SanitizeAsFileName(string title)
    {
        var invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = new string(title.Where(c => !invalidChars.Contains(c)).ToArray()).Trim();
        return string.IsNullOrWhiteSpace(sanitized) ? "export" : sanitized;
    }

    private bool CanExportVideo() => IsShaderLoaded && !IsExporting;

    /// <summary>
    /// Turns the first <c>Videotoy.Core.ExportSettingsValidator.ExportSettingsIssue</c>
    /// reported by <c>validate</c> into a short, UI-ready sentence. Only the
    /// first issue is shown — consistent with how other validation summaries
    /// are surfaced in this panel (e.g. <see cref="ExportErrorSummary"/> for
    /// FFmpeg failures). The actual pattern matching lives in F# via
    /// <c>ExportSettingsValidator.describeFirstIssue</c>, since matching on
    /// F# discriminated union cases directly from C# is fragile.
    /// </summary>
    private static string DescribeFirstValidationIssue(
        Microsoft.FSharp.Collections.FSharpList<Videotoy.Core.ExportSettingsValidator.ExportSettingsIssue> issues)
    {
        return Videotoy.Core.ExportSettingsValidator.describeFirstIssue(issues);
    }

    /// <summary>
    /// Résout le chemin absolu du fichier audio source à muxer avec la vidéo
    /// exportée, lorsque le shader chargé possède un <c>iChannel</c> audio
    /// (type <c>Music</c> ou <c>MusicStream</c>). Le chemin déclaré dans le
    /// shader (<see cref="Videotoy.Core.ShaderModel.firstAudioChannelPath"/>)
    /// est résolu par rapport au dossier du fichier shader, exactement comme
    /// le fait déjà <see cref="ShaderFileService"/> au chargement. Ne
    /// détermine délibérément aucune durée : c'est
    /// <see cref="VideoExportPipeline.RunAsync"/> qui calcule la durée
    /// effective à partir du nombre de frames réellement rendu, pour rester
    /// strictement aligné sur la timeline de rendu déterministe même en mode
    /// boucle parfaite. Retourne <c>null</c> si le shader n'utilise aucune
    /// entrée audio, ou si le fichier résolu n'existe plus sur disque.
    /// </summary>
    private static string? ResolveExportAudioSourceFilePath(LoadedShader loadedShader)
    {
        var declaredPath = Videotoy.Core.ShaderModel.firstAudioChannelPath(loadedShader.Project);
        if (declaredPath is null)
        {
            return null;
        }

        var baseDirectory = Path.GetDirectoryName(loadedShader.Project.SourceFilePath) ?? string.Empty;
        var resolvedPath = Path.IsPathRooted(declaredPath.Value)
            ? declaredPath.Value
            : Path.Combine(baseDirectory, declaredPath.Value);

        return File.Exists(resolvedPath) ? resolvedPath : null;
    }

    /// <summary>
    /// Annule proprement l'export en cours : signale le token d'annulation,
    /// que <see cref="Videotoy.Ffmpeg.VideoExportPipeline"/> propage jusqu'à
    /// <see cref="Videotoy.Ffmpeg.FfmpegService.Cancel"/> pour tuer le
    /// process FFmpeg (et son arbre) et nettoyer ses ressources.
    /// </summary>
    [RelayCommand(CanExecute = nameof(IsExporting))]
    private void CancelExport()
    {
        _exportCancellationTokenSource?.Cancel();
        StatusMessage = "Cancelling export...";
    }

    private void OnExportProgress(VideoExportProgress progress)
    {
        ExportCurrentFrame = progress.CurrentFrameNumber;
        ExportTotalFrames = progress.TotalFrameCount;
        ExportProgressPercent = progress.ProgressFraction * 100.0;
        ExportRemainingTimeText = FormatRemainingTime(progress.EstimatedRemainingSeconds);
    }

    /// <summary>
    /// How long a toast stays visible before auto-dismissing itself. Kept
    /// short for success confirmations and errors alike, so the panel never
    /// accumulates stale notifications the user has to clear by hand.
    /// </summary>
    private static readonly TimeSpan ToastDisplayDuration = TimeSpan.FromSeconds(5);

    /// <summary>
    /// Queues a non-intrusive toast notification (<see cref="Toasts"/>) and
    /// schedules its automatic removal after <see cref="ToastDisplayDuration"/>.
    /// Used for export outcomes (success, cancellation is intentionally
    /// silent, and failure) so the user gets a clear, unobtrusive signal
    /// without a blocking dialog interrupting their workflow.
    /// </summary>
    private void ShowToast(ToastSeverity severity, string title, string message)
    {
        var toast = new ToastNotificationViewModel
        {
            Id = Guid.NewGuid(),
            Severity = severity,
            Title = title,
            Message = message
        };

        Toasts.Add(toast);

        var timer = new DispatcherTimer { Interval = ToastDisplayDuration };
        timer.Tick += (_, _) =>
        {
            timer.Stop();
            Toasts.Remove(toast);
        };
        timer.Start();
    }

    [RelayCommand]
    private void DismissToast(ToastNotificationViewModel toast)
    {
        Toasts.Remove(toast);
    }

    private string FormatRemainingTime(double? remainingSeconds)
    {
        if (remainingSeconds is not { } seconds || double.IsNaN(seconds) || double.IsInfinity(seconds))
        {
            return _localizationService.GetString("export.progress.estimating");
        }

        var remaining = TimeSpan.FromSeconds(Math.Max(0.0, seconds));
        return remaining.TotalHours >= 1.0
            ? remaining.ToString(@"h\:mm\:ss")
            : remaining.ToString(@"mm\:ss");
    }

    public void LoadShaderFile(string filePath)
    {
        if (!ShaderFileService.IsSupportedShaderFile(filePath))
        {
            StatusMessage = $"Unsupported file type: {filePath}";
            return;
        }

        try
        {
            var loadedShader = _shaderFileService.Load(filePath);

            ShaderIssues.Clear();
            foreach (var issue in loadedShader.Issues)
            {
                ShaderIssues.Add(ShaderIssueViewModel.FromIssue(issue));
            }

            IsIssuesPanelOpen = ShaderIssues.Count > 0;
            LoadedShaderName = loadedShader.Project.Title;
            IsShaderLoaded = true;
            OutputFileName = SanitizeAsFileName(loadedShader.Project.Title);

            HasLoopSeamPreview = false;
            LoopSeamStartFrameImageSource = null;
            LoopSeamEndFrameImageSource = null;

            ApplyLoopPeriodDetection(loadedShader.Project);
            RestoreLoopSettings(filePath);

            StatusMessage = loadedShader.HasErrors
                ? $"Loaded '{LoadedShaderName}' with errors."
                : $"Loaded '{LoadedShaderName}'.";

            _recentFilesService.AddOrPromote(filePath);
            ReloadRecentShaders();

            if (!loadedShader.HasErrors)
            {
                InitializePreview(loadedShader);
                HasAudioChannel = ResolveExportAudioSourceFilePath(loadedShader) is not null;
                IncludeAudioInExport = true;
            }
            else
            {
                HasAudioChannel = false;
                CustomUniformGroups.Clear();
                HasCustomUniforms = false;
            }
        }
        catch (Exception ex)
        {
            StatusMessage = $"Failed to load shader: {ex.Message}";
        }
    }

    /// <summary>
    /// Runs <see cref="Videotoy.Core.LoopPeriodDetector.detectLoopPeriod"/>
    /// against the just-loaded shader's source and updates
    /// <see cref="HasDetectedLoopPeriod"/> / <see cref="DetectedLoopPeriodSeconds"/>
    /// / <see cref="HasMultipleDetectedLoopPeriods"/> /
    /// <see cref="DetectedLoopPeriodSourceText"/> accordingly. Purely
    /// informational: never touches <see cref="LoopDurationSeconds"/> or
    /// <see cref="IsSeamlessLoopModeEnabled"/> itself — applying the
    /// suggestion is always an explicit, user-triggered action via
    /// <see cref="ApplyDetectedLoopPeriodCommand"/>.
    /// </summary>
    private void ApplyLoopPeriodDetection(Videotoy.Core.ShaderModel.ShaderProject project)
    {
        var detection = Videotoy.Core.LoopPeriodDetector.detectLoopPeriod(project);

        if (detection.SuggestedCandidate is { Value: { } candidate })
        {
            HasDetectedLoopPeriod = true;
            DetectedLoopPeriodSeconds = candidate.PeriodSeconds;
            HasMultipleDetectedLoopPeriods = detection.AllCandidates.Length > 1;
            DetectedLoopPeriodSourceText = $"{candidate.SourceExpression} ({candidate.PassName})";
        }
        else
        {
            HasDetectedLoopPeriod = false;
            DetectedLoopPeriodSeconds = 0.0;
            HasMultipleDetectedLoopPeriods = false;
            DetectedLoopPeriodSourceText = string.Empty;
        }

        ApplyDetectedLoopPeriodCommand.NotifyCanExecuteChanged();
    }

    /// <summary>
    /// Restores the last-used "Duration Mode" state for
    /// <paramref name="filePath"/> from <see cref="_loopSettingsService"/>,
    /// if one was ever saved for this exact shader file. No-op — leaving the
    /// current panel defaults untouched — the first time a given shader file
    /// is opened.
    /// </summary>
    private void RestoreLoopSettings(string filePath)
    {
        var saved = _loopSettingsService.TryGet(filePath);
        if (saved is null)
        {
            return;
        }

        IsSeamlessLoopModeEnabled = saved.IsSeamlessLoopModeEnabled;
        LoopDurationSeconds = saved.LoopDurationSeconds;
    }

    /// <summary>
    /// Persists the current "Duration Mode" selection
    /// (<see cref="IsSeamlessLoopModeEnabled"/> / <see cref="LoopDurationSeconds"/>)
    /// for the currently loaded shader, so it's restored next time this
    /// specific shader file is opened. Called on every change to either
    /// value rather than only on export, so the last state is captured even
    /// if the user never actually exports.
    /// </summary>
    private void PersistLoopSettings()
    {
        if (_loadedShader is null)
        {
            return;
        }

        _loopSettingsService.SaveOrReplace(
            _loadedShader.Project.SourceFilePath,
            IsSeamlessLoopModeEnabled,
            LoopDurationSeconds);
    }

    /// <summary>
    /// Reconstruit intégralement <see cref="CustomUniformGroups"/> à partir
    /// des uniforms custom exposés par le shader qui vient d'être initialisé
    /// dans <see cref="_previewRenderer"/> : un groupe par uniform déclaré,
    /// initialisé à sa valeur par défaut. Chaque changement de slider est
    /// répercuté en direct sur <see cref="MultiPassRenderer.SetCustomUniformComponent"/>,
    /// donc sur la prochaine frame de prévisualisation rendue — sans
    /// recompilation ni re-chargement du shader.
    /// </summary>
    private void ReloadCustomUniformGroups()
    {
        CustomUniformGroups.Clear();

        foreach (var declaration in _previewRenderer.CustomUniformDeclarations)
        {
            CustomUniformGroups.Add(CustomUniformGroupViewModel.FromDeclaration(
                declaration,
                (name, componentIndex, value) => _previewRenderer.SetCustomUniformComponent(name, componentIndex, value)));
        }

        HasCustomUniforms = CustomUniformGroups.Count > 0;
    }

    private void InitializePreview(LoadedShader loadedShader)
    {
        _loadedShader = loadedShader;

        _previewRenderer.Initialize(RenderTargetSize.PreviewDefault, loadedShader.Project, loadedShader.HlslPasses);
        ReloadCustomUniformGroups();

        _previewBitmap = new WriteableBitmap(
            RenderTargetSize.PreviewDefault.Width,
            RenderTargetSize.PreviewDefault.Height,
            96,
            96,
            PixelFormats.Bgra32,
            null);
        PreviewImageSource = _previewBitmap;

        _previewClock.Stop();
        IsPlaying = false;
        _previewClock.Play();
        IsPlaying = true;

        TogglePlaybackCommand.NotifyCanExecuteChanged();
        StopPlaybackCommand.NotifyCanExecuteChanged();
    }

    /// <summary>
    /// Avance l'horloge de lecture d'un delta de temps réel écoulé et rend la frame
    /// correspondante dans le viewport. À appeler depuis la boucle de rafraîchissement
    /// de la fenêtre (CompositionTarget.Rendering) tant qu'un shader est chargé.
    /// </summary>
    public void AdvancePreview(double realDeltaSeconds)
    {
        if (!IsShaderLoaded || _isScrubbing)
        {
            return;
        }

        _previewClock.Advance(realDeltaSeconds);
        CurrentFps = realDeltaSeconds > 0.0 ? 1.0 / realDeltaSeconds : 0.0;
    }

    private void OnPreviewClockTimeChanged(object? sender, EventArgs e)
    {
        PlaybackTimeSeconds = _previewClock.CurrentTimeSeconds;
        RenderCurrentFrame();
    }

    private void RenderCurrentFrame()
    {
        if (_previewBitmap is null || _loadedShader is null)
        {
            return;
        }

        var pixels = _previewRenderer.RenderFrame(_previewClock.CurrentTimeSeconds, 0.0, CurrentFrame);
        if (pixels.Length == 0)
        {
            return;
        }

        _previewBitmap.WritePixels(
            new System.Windows.Int32Rect(0, 0, _previewBitmap.PixelWidth, _previewBitmap.PixelHeight),
            pixels,
            _previewBitmap.PixelWidth * 4,
            0);

        CurrentFrame++;
    }

    private void ReloadRecentShaders()
    {
        RecentShaders.Clear();
        foreach (var entry in _recentFilesService.Load())
        {
            RecentShaders.Add(entry);
        }
    }

    partial void OnIsShaderLoadedChanged(bool value)
    {
        TogglePlaybackCommand.NotifyCanExecuteChanged();
        StopPlaybackCommand.NotifyCanExecuteChanged();
        ExportVideoCommand.NotifyCanExecuteChanged();
        GenerateLoopSeamPreviewCommand.NotifyCanExecuteChanged();
    }

    partial void OnIsExportingChanged(bool value)
    {
        ExportVideoCommand.NotifyCanExecuteChanged();
        CancelExportCommand.NotifyCanExecuteChanged();
        GenerateLoopSeamPreviewCommand.NotifyCanExecuteChanged();
    }

    partial void OnIsGeneratingLoopSeamPreviewChanged(bool value) => GenerateLoopSeamPreviewCommand.NotifyCanExecuteChanged();

    partial void OnLoopDurationSecondsChanged(double value)
    {
        _previewClock.LoopDurationSeconds = value;
        RecalculateExportPreview();
        PersistLoopSettings();
    }

    partial void OnSelectedResolutionPresetChanged(ResolutionPresetOption value) => RecalculateExportPreview();

    partial void OnCustomResolutionWidthChanged(int value) => RecalculateExportPreview();

    partial void OnCustomResolutionHeightChanged(int value) => RecalculateExportPreview();

    partial void OnSelectedFrameRatePresetChanged(FrameRatePresetOption value) => RecalculateExportPreview();

    partial void OnCustomFrameRateValueChanged(double value) => RecalculateExportPreview();

    partial void OnIsSeamlessLoopModeEnabledChanged(bool value)
    {
        RecalculateExportPreview();
        PersistLoopSettings();
    }

    partial void OnIsLoopEndFrameExclusiveChanged(bool value) => RecalculateExportPreview();

    partial void OnHasLoopRoundingMismatchChanged(bool value) => ApplyAssistedLoopRoundingCommand.NotifyCanExecuteChanged();

    partial void OnHasDetectedLoopPeriodChanged(bool value) => ApplyDetectedLoopPeriodCommand.NotifyCanExecuteChanged();

    partial void OnManualDurationUnitChanged(DurationUnit value)
    {
        OnPropertyChanged(nameof(ManualDurationUnitIndex));
        RecalculateExportPreview();
    }

    partial void OnManualDurationValueChanged(double value) => RecalculateExportPreview();

    partial void OnHasAudioChannelChanged(bool value) => RecalculateExportPreview();

    partial void OnIncludeAudioInExportChanged(bool value) => RecalculateExportPreview();

    partial void OnNewExportPresetNameChanged(string value) => SaveExportPresetCommand.NotifyCanExecuteChanged();

    partial void OnSelectedExportPresetChanged(ExportPreset? value)
    {
        LoadExportPresetCommand.NotifyCanExecuteChanged();
        DeleteExportPresetCommand.NotifyCanExecuteChanged();
    }
}
